macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-xcode:latest

nix_shell_task:
  timeout_in: 120m
  environment:
    CACHIX_AUTH_TOKEN: ENCRYPTED[!236a7efb3d930235464b021112417f9d6340798949f3cd06d3ad3fa6540ee28ea758499a9770d155805cb9d29d2e2157!]
    NIX_CONFIG: "extra-experimental-features = nix-command"

  install_nix_script: sh <(curl -L https://nixos.org/nix/install)

  add_trusted_user_script: echo "trusted-users = root $USER" | sudo tee -a /etc/nix/nix.conf

  restart_nix_daemon_script: sudo launchctl kickstart -k system/org.nixos.nix-daemon

  install_cachix_script: |
    source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh > /dev/null 2>&1
    source /nix/var/nix/profiles/default/etc/profile.d/nix.sh > /dev/null 2>&1
    nix-env -iA cachix -f https://cachix.org/api/v1/install
    cachix use jost-s

  nix_shell_script: |
    source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh > /dev/null 2>&1
    source /nix/var/nix/profiles/default/etc/profile.d/nix.sh > /dev/null 2>&1
    nix build | cachix push jost-s
    # nix-build holochain.nix | cachix push jost-s
