name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: git clone https://github.com/holochain/holochain && cd holochain && git tag | grep holochain- | sort -V | tail -1

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
